// scripts/import-all.ts
// Orchestrator: run every extension-publication parser, merge results, and
// emit the verified curated catalog to src/assets/catalog.generated.ts.
//
// Run: npm run import:catalog
//
// Conflict resolution: when multiple parsers emit a plant with the same id,
// the one with `provenance.verified === true` wins. Among multiple verified
// entries, the first one wins (parser order is significant — list authoritative
// sources earlier in `PARSERS` below).

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Plant } from '../src/domain/types';
import { parseUsuExtension } from './import/usu-extension';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../src/assets/catalog.generated.ts');

// List parsers in priority order. First-listed wins on id collision.
const PARSERS: Array<() => Promise<Plant[]>> = [
  parseUsuExtension,
  // Add future parsers here:
  //   parseCornellExtension,
  //   parseUMaineExtension,
];

async function main() {
  const merged = new Map<string, Plant>();
  let totalEmitted = 0;
  let collisionsSkipped = 0;

  for (const parse of PARSERS) {
    const plants = await parse();
    totalEmitted += plants.length;
    for (const p of plants) {
      const existing = merged.get(p.id);
      if (existing) {
        // Conflict: keep the existing entry only if it's verified and
        // the new one isn't. Otherwise the parser order rules.
        if (existing.provenance?.verified && !p.provenance?.verified) {
          collisionsSkipped += 1;
          continue;
        }
        // Otherwise we already have an entry from a higher-priority parser —
        // the higher-priority entry wins.
        collisionsSkipped += 1;
        continue;
      }
      if (!p.provenance) {
        throw new Error(
          `[import-all] parser emitted "${p.id}" with no provenance — every imported entry MUST cite a source`,
        );
      }
      merged.set(p.id, p);
    }
  }

  const output = renderCatalog(Array.from(merged.values()));
  writeFileSync(OUTPUT_PATH, output, 'utf-8');

  console.log(`[import-all] parsers ran: ${PARSERS.length}`);
  console.log(`[import-all] entries emitted: ${totalEmitted}`);
  console.log(`[import-all] entries kept after de-dup: ${merged.size}`);
  console.log(`[import-all] collisions skipped: ${collisionsSkipped}`);
  console.log(`[import-all] wrote ${OUTPUT_PATH}`);
}

function renderCatalog(plants: Plant[]): string {
  const sorted = [...plants].sort((a, b) => a.id.localeCompare(b.id));
  return `// src/assets/catalog.generated.ts
// AUTO-GENERATED by scripts/import-all.ts. Do not edit by hand.
//
// Re-run \`npm run import:catalog\` after updating any extension PDF or parser.
// Generated at: ${new Date().toISOString()}
// Entry count: ${sorted.length}

import type { Plant } from '../domain/types';

export const generatedCatalog: readonly Plant[] = ${JSON.stringify(sorted, null, 2)} as const;
`;
}

main().catch((err) => {
  console.error('[import-all] failed:', err);
  process.exit(1);
});
