// src/assets/catalog.generated.ts
// AUTO-GENERATED by scripts/import-all.ts. Do not edit by hand.
//
// Re-run `npm run import:catalog` after updating any extension PDF or parser.
// Generated at: 2026-04-27T22:57:23.946Z
// Entry count: 45

import type { Plant } from '../domain/types';

export const generatedCatalog: readonly Plant[] = [
  {
    "id": "basil",
    "source": "curated",
    "name": "Basil",
    "category": "herb",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 45,
      "daysToGermination": [
        5,
        14
      ],
      "daysToMaturity": 60,
      "harvestWindowDays": 60,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": true,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Basil\".) | Cornell verifies start-method (S) and frost-relative window (June - July (multiple successions), offsetDays=45). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Basil\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Ocimum basilicum"
  },
  {
    "id": "beans",
    "source": "curated",
    "name": "Beans",
    "category": "legume",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 45,
      "daysToGermination": [
        6,
        10
      ],
      "daysToMaturity": 83,
      "harvestWindowDays": 21,
      "frostTolerance": "hardy",
      "hasFlowering": true,
      "requiresHardening": false,
      "season": "cool",
      "successionIntervalDays": 14,
      "maxSuccessions": 4
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Beans, All\".) | Cornell verifies start-method (S) and frost-relative window (June - July (multiple successions), offsetDays=45). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Beans, All\".) | Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Beans, Bush\" (offset NOT extracted — fall-anchored). (Source label: \"Beans, Bush\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Beans, Bush\" (offset NOT extracted — fall-anchored). (Source label: \"Beans, Bush\".) | USU verifies daysToMaturity (65-100 → midpoint 83). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Beans\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Phaseolus vulgaris"
  },
  {
    "id": "beet",
    "source": "curated",
    "name": "Beet",
    "category": "root",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -21,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 55,
      "harvestWindowDays": 21,
      "frostTolerance": "half-hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Beet\" (offset NOT extracted — fall-anchored). (Source label: \"Beet\".) | Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Beet\" (offset NOT extracted — fall-anchored). (Source label: \"Beet\".) | Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Beet\".) | USU verifies daysToMaturity (50-60 → midpoint 55). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Beets\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "startMethod",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Beta vulgaris"
  },
  {
    "id": "broccoli",
    "source": "curated",
    "name": "Broccoli",
    "category": "brassica",
    "timing": {
      "startMethod": "indoor-start",
      "weeksIndoorBeforeLastFrost": 6,
      "transplantOffsetDaysFromLastFrost": -28,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 60,
      "harvestWindowDays": 21,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": true,
      "season": "cool",
      "daysToHardenOff": 7
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (T) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Broccoli\".) | Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Broccoli\" (offset NOT extracted — fall-anchored). (Source label: \"Broccoli\".) | UMaine verifies weeksIndoorBeforeLastFrost (5-7 → midpoint 6) and daysToGermination (1-2 weeks → 7-14 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Broccoli\".) | USU verifies daysToMaturity (50-70 → midpoint 60). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Brocolli\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Brassica oleracea var. italica"
  },
  {
    "id": "brussels-sprouts",
    "source": "curated",
    "name": "Brussels Sprouts",
    "category": "brassica",
    "timing": {
      "startMethod": "indoor-start",
      "weeksIndoorBeforeLastFrost": 5,
      "transplantOffsetDaysFromLastFrost": 0,
      "daysToGermination": [
        14,
        14
      ],
      "daysToMaturity": 131,
      "harvestWindowDays": 30,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": true,
      "season": "cool",
      "daysToHardenOff": 7
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Brussels Sprouts\" (offset NOT extracted — fall-anchored). (Source label: \"Brussels Sprouts\".) | UMaine verifies weeksIndoorBeforeLastFrost (4-6 → midpoint 5) and daysToGermination (1-2 weeks → 7-14 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Brussels Sprout\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity. Reference frost: last spring 05-01, first fall 10-01. (Brussel Sprouts has footnote (7) \"transplant-best\"; Cornell handles the transplant offset.) (Source label: \"Brussel Sprouts\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "startMethod",
        "daysToMaturity"
      ]
    },
    "scientificName": "Brassica oleracea var. gemmifera"
  },
  {
    "id": "cabbage",
    "source": "curated",
    "name": "Cabbage",
    "category": "brassica",
    "timing": {
      "startMethod": "indoor-start",
      "directSowOffsetDaysFromLastFrost": 0,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 60,
      "harvestWindowDays": 21,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": true,
      "season": "cool",
      "transplantOffsetDaysFromLastFrost": -28,
      "weeksIndoorBeforeLastFrost": 7
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Cabbage\" (offset NOT extracted — fall-anchored). (Source label: \"Cabbage\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Cabbage\" (offset NOT extracted — fall-anchored). (Source label: \"Cabbage\".) | Cornell verifies start-method (T) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Cabbage\".) | UMaine verifies weeksIndoorBeforeLastFrost (5-8 → midpoint 7) and daysToGermination (1-2 weeks → 7-14 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Cabbage\".) | USU verifies daysToMaturity (50-70 → midpoint 60). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Cabbage\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "startMethod",
        "transplantOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Brassica oleracea var. capitata"
  },
  {
    "id": "carrot",
    "source": "curated",
    "name": "Carrot",
    "category": "root",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -14,
      "daysToGermination": [
        21,
        21
      ],
      "daysToMaturity": 75,
      "harvestWindowDays": 30,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Carrot\" (offset NOT extracted — fall-anchored). (Source label: \"Carrot\".) | Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Carrot\".) | Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Carrot\" (offset NOT extracted — fall-anchored). (Source label: \"Carrot\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Carrots\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "startMethod",
        "directSowOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Daucus carota"
  },
  {
    "id": "cauliflower",
    "source": "curated",
    "name": "Cauliflower",
    "category": "brassica",
    "timing": {
      "startMethod": "indoor-start",
      "weeksIndoorBeforeLastFrost": 7,
      "transplantOffsetDaysFromLastFrost": -21,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 60,
      "harvestWindowDays": 14,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": true,
      "season": "cool",
      "daysToHardenOff": 7
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (T) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Cauliflower\".) | Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Cauliflower\" (offset NOT extracted — fall-anchored). (Source label: \"Cauliflower\".) | UMaine verifies weeksIndoorBeforeLastFrost (5-8 → midpoint 7) and daysToGermination (1-2 weeks → 7-14 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Cauliflower\".) | USU verifies daysToMaturity (50-70 → midpoint 60). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Cauliower\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Brassica oleracea var. botrytis"
  },
  {
    "id": "celery",
    "source": "curated",
    "name": "Celery",
    "category": "other",
    "timing": {
      "startMethod": "direct-sow",
      "weeksIndoorBeforeLastFrost": 10,
      "transplantOffsetDaysFromLastFrost": -21,
      "daysToGermination": [
        21,
        21
      ],
      "daysToMaturity": 120,
      "harvestWindowDays": 30,
      "frostTolerance": "half-hardy",
      "hasFlowering": false,
      "requiresHardening": true,
      "season": "cool",
      "directSowOffsetDaysFromLastFrost": -7
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (T) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Celery\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Celery\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Apium graveolens"
  },
  {
    "id": "chard",
    "source": "curated",
    "name": "Chard",
    "category": "leafy-green",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 45,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 55,
      "harvestWindowDays": 60,
      "frostTolerance": "tender",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Chard\" (offset NOT extracted — fall-anchored). (Source label: \"Chard\".) | Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Chard\".) | Cornell verifies start-method (S) and frost-relative window (June - July (multiple successions), offsetDays=45). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Chard\".) | USU verifies daysToMaturity (50-60 → midpoint 55). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Swiss Chard\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "startMethod",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Beta vulgaris subsp. vulgaris"
  },
  {
    "id": "chinese-cabbage",
    "source": "curated",
    "name": "Chinese Cabbage",
    "category": "brassica",
    "timing": {
      "startMethod": "indoor-start",
      "directSowOffsetDaysFromLastFrost": 0,
      "daysToGermination": [
        14,
        14
      ],
      "daysToMaturity": 91,
      "harvestWindowDays": 14,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Chinese Cabbage\" (offset NOT extracted — fall-anchored). (Source label: \"Chinese Cabbage\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity. Reference frost: last spring 05-01, first fall 10-01. (Cabbage, Chinese has footnote (7) \"transplant-best\"; Cornell handles the transplant offset.) (Source label: \"Cabbage, Chinese\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "startMethod",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Brassica rapa subsp. pekinensis"
  },
  {
    "id": "chives",
    "source": "curated",
    "name": "Chives",
    "category": "allium",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -21,
      "daysToGermination": [
        10,
        21
      ],
      "daysToMaturity": 80,
      "harvestWindowDays": 90,
      "frostTolerance": "half-hardy",
      "hasFlowering": true,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Chives\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Allium schoenoprasum"
  },
  {
    "id": "cilantro",
    "source": "curated",
    "name": "Cilantro",
    "category": "herb",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 50,
      "harvestWindowDays": 21,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Cilantro\".) | Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Cilantro\" (offset NOT extracted — fall-anchored). (Source label: \"Cilantro\".) | Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Cilantro\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Coriandrum sativum"
  },
  {
    "id": "collards",
    "source": "curated",
    "name": "Collards",
    "category": "brassica",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -14,
      "daysToGermination": [
        14,
        14
      ],
      "daysToMaturity": 80,
      "harvestWindowDays": 60,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool",
      "transplantOffsetDaysFromLastFrost": -28
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Collards\" (offset NOT extracted — fall-anchored). (Source label: \"Collards\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Collards\" (offset NOT extracted — fall-anchored). (Source label: \"Collards\".) | Cornell verifies start-method (T) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Collards\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Collards\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "startMethod",
        "transplantOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Brassica oleracea var. acephala"
  },
  {
    "id": "cucumber",
    "source": "curated",
    "name": "Cucumber",
    "category": "fruiting-vegetable",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 90,
      "harvestWindowDays": 30,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": true,
      "season": "warm",
      "weeksIndoorBeforeLastFrost": 3
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Cucumber\".) | UMaine verifies weeksIndoorBeforeLastFrost (2-3 → midpoint 3) and daysToGermination (1-2 weeks → 7-14 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Cucumbers\".) | USU verifies daysToMaturity (85-95 → midpoint 90). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Cucumber\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Cucumis sativus"
  },
  {
    "id": "dill",
    "source": "curated",
    "name": "Dill",
    "category": "herb",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        7,
        21
      ],
      "daysToMaturity": 55,
      "harvestWindowDays": 30,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell verifies start-method (S) and frost-relative window (June - July (multiple successions), offsetDays=45). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Dill\".) | Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Dill\" (offset NOT extracted — fall-anchored). (Source label: \"Dill\".) | Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Dill\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Anethum graveolens"
  },
  {
    "id": "eggplant",
    "source": "curated",
    "name": "Eggplant",
    "category": "fruiting-vegetable",
    "timing": {
      "startMethod": "indoor-start",
      "weeksIndoorBeforeLastFrost": 9,
      "transplantOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 60,
      "harvestWindowDays": 30,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": true,
      "season": "warm",
      "daysToHardenOff": 7
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Colorado State University Extension (Master Gardener)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (T) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Eggplant\".) | UMaine verifies weeksIndoorBeforeLastFrost (8-9 → midpoint 9) and daysToGermination (2-3 weeks → 14-21 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Eggplant\".) | CSU verifies daysToGermination (7-14), daysToMaturity (60T), season=warm, startMethod=indoor-start, frostTolerance=tender (from CSU prose). (Source label: \"Eggplant\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Solanum melongena"
  },
  {
    "id": "fennel",
    "source": "curated",
    "name": "Fennel",
    "category": "herb",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 65,
      "harvestWindowDays": 21,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell verifies start-method (S) and frost-relative window (June - July (multiple successions), offsetDays=45). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Fennel\".) | Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Fennel\" (offset NOT extracted — fall-anchored). (Source label: \"Fennel\".) | Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Fennel\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Foeniculum vulgare"
  },
  {
    "id": "garlic",
    "source": "curated",
    "name": "Garlic",
    "category": "allium",
    "timing": {
      "startMethod": "direct-sow",
      "daysToGermination": [
        14,
        28
      ],
      "daysToMaturity": 110,
      "harvestWindowDays": 21,
      "frostTolerance": "half-hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool",
      "directSowOffsetDaysFromLastFrost": 0
    },
    "provenance": {
      "source": "Utah State University Extension",
      "publication": "Wasatch Front Vegetable Chart (Suggested Vegetable Planting Dates)",
      "url": "https://extension.usu.edu/yardandgarden/files/Planting-Guide.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "USU verifies daysToMaturity (100-120 → midpoint 110). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Garlic\".)",
      "page": 1,
      "verifiedFields": [
        "daysToMaturity"
      ]
    },
    "scientificName": "Allium sativum"
  },
  {
    "id": "green-onion",
    "source": "curated",
    "name": "Green Onion",
    "category": "allium",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -14,
      "daysToGermination": [
        10,
        10
      ],
      "daysToMaturity": 70,
      "harvestWindowDays": 21,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Green Onion (Sets)\" (offset NOT extracted — fall-anchored). (Source label: \"Green Onion (Sets)\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost, harvestWindowDays. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Onion, Bunching\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "startMethod",
        "daysToGermination",
        "daysToMaturity",
        "directSowOffsetDaysFromLastFrost",
        "harvestWindowDays"
      ]
    },
    "scientificName": "Allium fistulosum"
  },
  {
    "id": "heat-resistant-lettuce",
    "source": "curated",
    "name": "Heat-Resistant Lettuce",
    "category": "leafy-green",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 45,
      "daysToGermination": [
        4,
        10
      ],
      "daysToMaturity": 55,
      "harvestWindowDays": 21,
      "frostTolerance": "tender",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell verifies start-method (S) and frost-relative window (June - July (multiple successions), offsetDays=45). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Heat Resistant Lettuce\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Lactuca sativa"
  },
  {
    "id": "kale",
    "source": "curated",
    "name": "Kale",
    "category": "brassica",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -28,
      "daysToGermination": [
        5,
        10
      ],
      "daysToMaturity": 55,
      "harvestWindowDays": 60,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Kale\" (offset NOT extracted — fall-anchored). (Source label: \"Kale\".) | Cornell verifies start-method (S) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Kale\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Kale\" (offset NOT extracted — fall-anchored). (Source label: \"Kale\".) | USU verifies daysToMaturity (50-60 → midpoint 55). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Kale\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "startMethod",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Brassica oleracea var. sabellica"
  },
  {
    "id": "kohlrabi",
    "source": "curated",
    "name": "Kohlrabi",
    "category": "brassica",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -21,
      "daysToGermination": [
        10,
        10
      ],
      "daysToMaturity": 50,
      "harvestWindowDays": 14,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Kohlrabi\" (offset NOT extracted — fall-anchored). (Source label: \"Kohlrabi\".) | Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Kohlrabi\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Kohlrabi\" (offset NOT extracted — fall-anchored). (Source label: \"Kohlrabi\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Kohlrabi\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season",
        "startMethod",
        "directSowOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Brassica oleracea var. gongylodes"
  },
  {
    "id": "leaf-lettuce",
    "source": "curated",
    "name": "Leaf Lettuce",
    "category": "leafy-green",
    "timing": {
      "startMethod": "indoor-start",
      "weeksIndoorBeforeLastFrost": 4,
      "transplantOffsetDaysFromLastFrost": -28,
      "daysToGermination": [
        14,
        21
      ],
      "daysToMaturity": 53,
      "harvestWindowDays": 21,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool",
      "successionIntervalDays": 14,
      "maxSuccessions": 4
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (T) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Leaf Lettuce\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Leaf Lettuce\" (offset NOT extracted — fall-anchored). (Source label: \"Leaf Lettuce\".) | Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Leaf Lettuce\" (offset NOT extracted — fall-anchored). (Source label: \"Leaf Lettuce\".) | UMaine verifies weeksIndoorBeforeLastFrost (3-5 → midpoint 4) and daysToGermination (2-3 weeks → 14-21 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Head Lettuce\".) | USU verifies daysToMaturity (45-60 → midpoint 53). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Lettuce (leafy types)\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Lactuca sativa"
  },
  {
    "id": "leafy-greens",
    "source": "curated",
    "name": "Leafy Greens",
    "category": "leafy-green",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 0,
      "daysToGermination": [
        5,
        14
      ],
      "daysToMaturity": 45,
      "harvestWindowDays": 30,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Leafy Greens\" (offset NOT extracted — fall-anchored). (Source label: \"Leafy Greens\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season"
      ]
    }
  },
  {
    "id": "leek",
    "source": "curated",
    "name": "Leek",
    "category": "allium",
    "timing": {
      "startMethod": "indoor-start",
      "weeksIndoorBeforeLastFrost": 11,
      "transplantOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        14,
        21
      ],
      "daysToMaturity": 110,
      "harvestWindowDays": 30,
      "frostTolerance": "tender",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (T) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Leek\".) | UMaine verifies weeksIndoorBeforeLastFrost (10-12 → midpoint 11) and daysToGermination (2-3 weeks → 14-21 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Leeks\".) | USU verifies daysToMaturity (100-120 → midpoint 110). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Leeks\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Allium ampeloprasum"
  },
  {
    "id": "melon",
    "source": "curated",
    "name": "Melon",
    "category": "fruiting-vegetable",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        4,
        10
      ],
      "daysToMaturity": 90,
      "harvestWindowDays": 21,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": true,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Melons\".) | USU verifies daysToMaturity (85-95 → midpoint 90). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Melons\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Cucumis melo"
  },
  {
    "id": "mustard",
    "source": "curated",
    "name": "Mustard",
    "category": "brassica",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -21,
      "daysToGermination": [
        4,
        10
      ],
      "daysToMaturity": 45,
      "harvestWindowDays": 21,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Georgia Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Mustard\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Mustard\" (offset NOT extracted — fall-anchored). (Source label: \"Mustard\".) | Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Mustard\" (offset NOT extracted — fall-anchored). (Source label: \"Mustard\".) | UGA verifies daysToMaturity (40-50 → midpoint 45). (Source label: \"mustard\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Brassica juncea"
  },
  {
    "id": "new-zealand-spinach",
    "source": "curated",
    "name": "New Zealand Spinach",
    "category": "leafy-green",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        10,
        20
      ],
      "daysToMaturity": 60,
      "harvestWindowDays": 60,
      "frostTolerance": "tender",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell verifies start-method (S) and frost-relative window (June - July (multiple successions), offsetDays=45). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"N.Z. Spinach\".) | Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"N.Z. Spinach\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Tetragonia tetragonoides"
  },
  {
    "id": "okra",
    "source": "curated",
    "name": "Okra",
    "category": "fruiting-vegetable",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 30,
      "daysToGermination": [
        14,
        14
      ],
      "daysToMaturity": 55,
      "harvestWindowDays": 42,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Okra\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost, harvestWindowDays. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Okra\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity",
        "harvestWindowDays"
      ]
    },
    "scientificName": "Abelmoschus esculentus"
  },
  {
    "id": "onion",
    "source": "curated",
    "name": "Onion",
    "category": "allium",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -21,
      "daysToGermination": [
        14,
        21
      ],
      "daysToMaturity": 110,
      "harvestWindowDays": 21,
      "frostTolerance": "half-hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool",
      "weeksIndoorBeforeLastFrost": 7
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Onion (Sets)\".) | Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Onion (Sets)\".) | UMaine verifies weeksIndoorBeforeLastFrost (6-8 → midpoint 7) and daysToGermination (2-3 weeks → 14-21 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Onions (globle)\".) | USU verifies daysToMaturity (100-120 → midpoint 110). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Onions\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Allium cepa"
  },
  {
    "id": "parsley",
    "source": "curated",
    "name": "Parsley",
    "category": "herb",
    "timing": {
      "startMethod": "indoor-start",
      "weeksIndoorBeforeLastFrost": 8,
      "transplantOffsetDaysFromLastFrost": -21,
      "daysToGermination": [
        14,
        28
      ],
      "daysToMaturity": 75,
      "harvestWindowDays": 90,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell verifies start-method (T) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Parsley\".) | Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Parsley\" (offset NOT extracted — fall-anchored). (Source label: \"Parsley\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Parsley\" (offset NOT extracted — fall-anchored). (Source label: \"Parsley\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Petroselinum crispum"
  },
  {
    "id": "parsnip",
    "source": "curated",
    "name": "Parsnip",
    "category": "root",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -14,
      "daysToGermination": [
        21,
        21
      ],
      "daysToMaturity": 110,
      "harvestWindowDays": 21,
      "frostTolerance": "half-hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Parsnip\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost, harvestWindowDays. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Parsnip\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity",
        "harvestWindowDays"
      ]
    },
    "scientificName": "Pastinaca sativa"
  },
  {
    "id": "peas",
    "source": "curated",
    "name": "Peas",
    "category": "legume",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -28,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 60,
      "harvestWindowDays": 14,
      "frostTolerance": "hardy",
      "hasFlowering": true,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Peas\".) | USU verifies daysToMaturity (50-70 → midpoint 60). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Peas\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Pisum sativum"
  },
  {
    "id": "pepper",
    "source": "curated",
    "name": "Pepper",
    "category": "fruiting-vegetable",
    "timing": {
      "startMethod": "indoor-start",
      "weeksIndoorBeforeLastFrost": 9,
      "transplantOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 80,
      "harvestWindowDays": 35,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": true,
      "season": "warm",
      "daysToHardenOff": 7
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (T) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Peppers\".) | UMaine verifies weeksIndoorBeforeLastFrost (8-10 → midpoint 9) and daysToGermination (1-2 weeks → 7-14 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Peppers\".) | USU verifies daysToMaturity (60-100 → midpoint 80). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Peppers\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Capsicum annuum"
  },
  {
    "id": "potato",
    "source": "curated",
    "name": "Potato",
    "category": "root",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        14,
        28
      ],
      "daysToMaturity": 80,
      "harvestWindowDays": 30,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Georgia Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Potato\".) | UGA verifies daysToMaturity (70-90 → midpoint 80). (Source label: \"potatoes, Irish\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Solanum tuberosum"
  },
  {
    "id": "radish",
    "source": "curated",
    "name": "Radish",
    "category": "root",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -28,
      "daysToGermination": [
        4,
        10
      ],
      "daysToMaturity": 30,
      "harvestWindowDays": 14,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool",
      "successionIntervalDays": 14,
      "maxSuccessions": 6
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (June - July (multiple successions), offsetDays=45). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Radish\".) | Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Radish\" (offset NOT extracted — fall-anchored). (Source label: \"Radish\".) | Cornell verifies start-method (S) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Radish\".) | Cornell fall column July 15 - Aug 1 (12-14 weeks before first fall frost): verifies frostTolerance + season for \"Radish\" (offset NOT extracted — fall-anchored). (Source label: \"Radish\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Radish\" (offset NOT extracted — fall-anchored). (Source label: \"Radish\".) | USU verifies daysToMaturity (25-35 → midpoint 30). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Radishes\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Raphanus sativus"
  },
  {
    "id": "rutabaga",
    "source": "curated",
    "name": "Rutabaga",
    "category": "root",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 30,
      "daysToGermination": [
        15,
        15
      ],
      "daysToMaturity": 90,
      "harvestWindowDays": 21,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Rutabaga\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost, harvestWindowDays. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Rutabaga\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity",
        "harvestWindowDays"
      ]
    },
    "scientificName": "Brassica napus var. napobrassica"
  },
  {
    "id": "spinach",
    "source": "curated",
    "name": "Spinach",
    "category": "leafy-green",
    "timing": {
      "startMethod": "direct-sow",
      "weeksIndoorBeforeLastFrost": 6,
      "transplantOffsetDaysFromLastFrost": -28,
      "daysToGermination": [
        14,
        14
      ],
      "daysToMaturity": 50,
      "harvestWindowDays": 28,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool",
      "directSowOffsetDaysFromLastFrost": -30
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (T) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Spinach\".) | Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Spinach\" (offset NOT extracted — fall-anchored). (Source label: \"Spinach\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost, harvestWindowDays. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Spinach\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity",
        "directSowOffsetDaysFromLastFrost",
        "harvestWindowDays"
      ]
    },
    "scientificName": "Spinacia oleracea"
  },
  {
    "id": "squash",
    "source": "curated",
    "name": "Squash",
    "category": "fruiting-vegetable",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        5,
        10
      ],
      "daysToMaturity": 90,
      "harvestWindowDays": 30,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": true,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (June - July (multiple successions), offsetDays=45). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Squash, Bush Summer Varieties\".) | Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Squash, All\".) | USU verifies daysToMaturity (80-100 → midpoint 90). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Winter Squash\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToMaturity"
      ]
    },
    "scientificName": "Cucurbita pepo"
  },
  {
    "id": "sweet-corn",
    "source": "curated",
    "name": "Sweet Corn",
    "category": "other",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 24,
      "daysToGermination": [
        14,
        14
      ],
      "daysToMaturity": 80,
      "harvestWindowDays": 14,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": false,
      "season": "warm",
      "successionIntervalDays": 14,
      "maxSuccessions": 3
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Sweet Corn\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost, harvestWindowDays. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Corn\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity",
        "harvestWindowDays"
      ]
    },
    "scientificName": "Zea mays"
  },
  {
    "id": "tomatillo",
    "source": "curated",
    "name": "Tomatillo",
    "category": "fruiting-vegetable",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        7,
        14
      ],
      "daysToMaturity": 75,
      "harvestWindowDays": 30,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": true,
      "season": "warm"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell verifies start-method (S) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Tomatillo\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost"
      ]
    },
    "scientificName": "Physalis philadelphica"
  },
  {
    "id": "tomato",
    "source": "curated",
    "name": "Tomato",
    "category": "fruiting-vegetable",
    "timing": {
      "startMethod": "indoor-start",
      "weeksIndoorBeforeLastFrost": 7,
      "transplantOffsetDaysFromLastFrost": 14,
      "daysToGermination": [
        14,
        21
      ],
      "daysToMaturity": 75,
      "harvestWindowDays": 35,
      "frostTolerance": "tender",
      "hasFlowering": true,
      "requiresHardening": true,
      "season": "warm",
      "daysToHardenOff": 7
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + University of Maine Cooperative Extension + Utah State University Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (T) and frost-relative window (May 15 - June 15 (cold-tender, around last frost), offsetDays=14). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Tomato\".) | UMaine verifies weeksIndoorBeforeLastFrost (6-8 → midpoint 7) and daysToGermination (2-3 weeks → 14-21 days). Other fields from typical-extension defaults — pending USU for daysToMaturity. (Source label: \"Tomatoes\".) | USU verifies daysToMaturity (60-90 → midpoint 75). Wasatch Front home last-spring-frost ≈ 05-07; planting-window bars on chart not extracted (image, not text). (Source label: \"Tomatoes\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "transplantOffsetDaysFromLastFrost",
        "weeksIndoorBeforeLastFrost",
        "daysToGermination",
        "daysToMaturity"
      ]
    },
    "scientificName": "Solanum lycopersicum"
  },
  {
    "id": "turnip",
    "source": "curated",
    "name": "Turnip",
    "category": "root",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": -28,
      "daysToGermination": [
        14,
        14
      ],
      "daysToMaturity": 55,
      "harvestWindowDays": 21,
      "frostTolerance": "half-hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension + Penn State Extension (York County Master Gardeners)",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": true,
      "note": "Cornell verifies start-method (S) and frost-relative window (April 1 - 30 (cold-hardy, early spring), offsetDays=-28). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Turnip\".) | Cornell fall column Aug 1 - 20 (10-12 weeks before first fall frost): verifies frostTolerance + season for \"Turnip\" (offset NOT extracted — fall-anchored). (Source label: \"Turnip\".) | Cornell verifies start-method (S) and frost-relative window (April 15 - 30 (cold-hardy), offsetDays=-21). Other timing fields from typical-extension defaults — pending UMaine/USU/PSU cross-reference. (Source label: \"Turnip\".) | PSU verifies: startMethod, season, daysToGermination, daysToMaturity, directSowOffsetDaysFromLastFrost, harvestWindowDays. Reference frost: last spring 05-01, first fall 10-01. (Source label: \"Turnip\".)",
      "page": 1,
      "verifiedFields": [
        "startMethod",
        "frostTolerance",
        "season",
        "directSowOffsetDaysFromLastFrost",
        "daysToGermination",
        "daysToMaturity",
        "harvestWindowDays"
      ]
    },
    "scientificName": "Brassica rapa subsp. rapa"
  },
  {
    "id": "turnip-greens",
    "source": "curated",
    "name": "Turnip Greens",
    "category": "brassica",
    "timing": {
      "startMethod": "direct-sow",
      "directSowOffsetDaysFromLastFrost": 0,
      "daysToGermination": [
        4,
        10
      ],
      "daysToMaturity": 35,
      "harvestWindowDays": 21,
      "frostTolerance": "hardy",
      "hasFlowering": false,
      "requiresHardening": false,
      "season": "cool"
    },
    "provenance": {
      "source": "Cornell Cooperative Extension",
      "publication": "Planting Guide for the New York City Area (rev. Aug 2020)",
      "url": "https://harvestny.cce.cornell.edu/uploads/doc_160.pdf",
      "retrieved": "2026-04-27",
      "license": "Land-grant Smith-Lever publication; redistributable with attribution.",
      "verified": false,
      "note": "Cornell fall column Aug 15 - Sept 1 (8-10 weeks before first fall frost): verifies frostTolerance + season for \"Turnip Greens\" (offset NOT extracted — fall-anchored). (Source label: \"Turnip Greens\".)",
      "page": 1,
      "verifiedFields": [
        "frostTolerance",
        "season"
      ]
    },
    "scientificName": "Brassica rapa subsp. rapa"
  }
] as const;
